// ======================================================================
// \title  FppConstantsAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for FPP constants
// ======================================================================

#ifndef MotionActivatedLight_Top_FppConstantsAc_HPP
#define MotionActivatedLight_Top_FppConstantsAc_HPP

#include "FpConfig.hpp"

namespace MotionActivatedLight {

  namespace Default {

    enum FppConstant_queueSize {
      queueSize = 10
    };

    enum FppConstant_stackSize {
      stackSize = 65536
    };

  }

}

#endif
