// ======================================================================
// \title  MotionActivatedLightTopologyAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for MotionActivatedLight topology
// ======================================================================

#ifndef MotionActivatedLight_MotionActivatedLightTopologyAc_HPP
#define MotionActivatedLight_MotionActivatedLightTopologyAc_HPP

#include "Drv/BlockDriver/BlockDriver.hpp"
#include "Drv/TcpClient/TcpClient.hpp"
#include "MotionActivatedLight/GoalMonitor/GoalMonitor.hpp"
#include "MotionActivatedLight/Light/Light.hpp"
#include "MotionActivatedLight/MotionSensor/MotionSensor.hpp"
#include "MotionActivatedLight/Top/MotionActivatedLightTopologyDefs.hpp"
#include "Svc/ActiveLogger/ActiveLogger.hpp"
#include "Svc/ActiveRateGroup/ActiveRateGroup.hpp"
#include "Svc/AssertFatalAdapter/AssertFatalAdapter.hpp"
#include "Svc/BufferManager/BufferManager.hpp"
#include "Svc/CmdDispatcher/CommandDispatcher.hpp"
#include "Svc/CmdSequencer/CmdSequencer.hpp"
#include "Svc/Deframer/Deframer.hpp"
#include "Svc/FatalHandler/FatalHandler.hpp"
#include "Svc/FileDownlink/FileDownlink.hpp"
#include "Svc/FileManager/FileManager.hpp"
#include "Svc/FileUplink/FileUplink.hpp"
#include "Svc/Framer/Framer.hpp"
#include "Svc/Health/Health.hpp"
#include "Svc/LinuxTime/LinuxTime.hpp"
#include "Svc/PassiveConsoleTextLogger/PassiveTextLogger.hpp"
#include "Svc/PrmDb/PrmDb.hpp"
#include "Svc/RateGroupDriver/RateGroupDriver.hpp"
#include "Svc/StaticMemory/StaticMemory.hpp"
#include "Svc/SystemResources/SystemResources.hpp"
#include "Svc/TlmChan/TlmChan.hpp"

namespace MotionActivatedLight {

  // ----------------------------------------------------------------------
  // Constants
  // ----------------------------------------------------------------------

  namespace ConfigConstants {
    namespace cmdSeq {
      enum {
        BUFFER_SIZE = 5*1024
      };
    }
    namespace comm {
      enum {
        PRIORITY = 100,
        STACK_SIZE = Default::stackSize
      };
    }
    namespace fileDownlink {
      enum {
        TIMEOUT = 1000,
        COOLDOWN = 1000,
        CYCLE_TIME = 1000,
        FILE_QUEUE_DEPTH = 10
      };
    }
    namespace fileUplinkBufferManager {
      enum {
        STORE_SIZE = 3000,
        QUEUE_SIZE = 30,
        MGR_ID = 200
      };
    }
    namespace health {
      enum {
        WATCHDOG_CODE = 0x123
      };
    }
  }

  namespace BaseIds {
    enum {
      blockDrv = 0x100,
      rateGroup1Comp = 0x200,
      rateGroup2Comp = 0x300,
      rateGroup3Comp = 0x400,
      cmdDisp = 0x500,
      cmdSeq = 0x600,
      fileDownlink = 0x700,
      fileManager = 0x800,
      fileUplink = 0x900,
      eventLogger = 0xB00,
      chanTlm = 0xC00,
      prmDb = 0xD00,
      health = 0x2000,
      comm = 0x4000,
      downlink = 0x4100,
      fatalAdapter = 0x4200,
      fatalHandler = 0x4300,
      fileUplinkBufferManager = 0x4400,
      linuxTime = 0x4500,
      rateGroupDriverComp = 0x4600,
      staticMemory = 0x4800,
      textLogger = 0x4900,
      uplink = 0x4A00,
      systemResources = 0x4B00,
      goalMonitor = 0x5000,
      motionSensor = 0x5100,
      light = 0x5200,
    };
  }

  namespace InstanceIds {
    enum {
      blockDrv,
      chanTlm,
      cmdDisp,
      cmdSeq,
      comm,
      downlink,
      eventLogger,
      fatalAdapter,
      fatalHandler,
      fileDownlink,
      fileManager,
      fileUplink,
      fileUplinkBufferManager,
      goalMonitor,
      health,
      light,
      linuxTime,
      motionSensor,
      prmDb,
      rateGroup1Comp,
      rateGroup2Comp,
      rateGroup3Comp,
      rateGroupDriverComp,
      staticMemory,
      systemResources,
      textLogger,
      uplink,
    };
  }

  namespace Priorities {
    enum {
      blockDrv = 140,
      chanTlm = 97,
      cmdDisp = 101,
      cmdSeq = 100,
      eventLogger = 98,
      fileDownlink = 100,
      fileManager = 100,
      fileUplink = 100,
      goalMonitor = 100,
      prmDb = 96,
      rateGroup1Comp = 120,
      rateGroup2Comp = 119,
      rateGroup3Comp = 118,
    };
  }

  namespace QueueSizes {
    enum {
      blockDrv = 10,
      chanTlm = 10,
      cmdDisp = 20,
      cmdSeq = 10,
      eventLogger = 10,
      fileDownlink = 30,
      fileManager = 30,
      fileUplink = 30,
      goalMonitor = 10,
      health = 25,
      prmDb = 10,
      rateGroup1Comp = 10,
      rateGroup2Comp = 10,
      rateGroup3Comp = 10,
    };
  }

  namespace StackSizes {
    enum {
      blockDrv = 65536,
      chanTlm = 65536,
      cmdDisp = 65536,
      cmdSeq = 65536,
      eventLogger = 65536,
      fileDownlink = 65536,
      fileManager = 65536,
      fileUplink = 65536,
      goalMonitor = 65536,
      prmDb = 65536,
      rateGroup1Comp = 65536,
      rateGroup2Comp = 65536,
      rateGroup3Comp = 65536,
    };
  }

  namespace TaskIds {
    enum {
      blockDrv,
      chanTlm,
      cmdDisp,
      cmdSeq,
      eventLogger,
      fileDownlink,
      fileManager,
      fileUplink,
      goalMonitor,
      prmDb,
      rateGroup1Comp,
      rateGroup2Comp,
      rateGroup3Comp,
    };
  }

  // ----------------------------------------------------------------------
  // Component instances
  // ----------------------------------------------------------------------

  //! blockDrv
  extern Drv::BlockDriver blockDrv;

  //! chanTlm
  extern Svc::TlmChan chanTlm;

  //! cmdDisp
  extern Svc::CommandDispatcher cmdDisp;

  //! cmdSeq
  extern Svc::CmdSequencer cmdSeq;

  //! comm
  extern Drv::TcpClient comm;

  //! downlink
  extern Svc::Framer downlink;

  //! eventLogger
  extern Svc::ActiveLogger eventLogger;

  //! fatalAdapter
  extern Svc::AssertFatalAdapter fatalAdapter;

  //! fatalHandler
  extern Svc::FatalHandler fatalHandler;

  //! fileDownlink
  extern Svc::FileDownlink fileDownlink;

  //! fileManager
  extern Svc::FileManager fileManager;

  //! fileUplink
  extern Svc::FileUplink fileUplink;

  //! fileUplinkBufferManager
  extern Svc::BufferManager fileUplinkBufferManager;

  //! goalMonitor
  extern GoalMonitor goalMonitor;

  //! health
  extern Svc::Health health;

  //! light
  extern Light light;

  //! linuxTime
  extern Svc::LinuxTime linuxTime;

  //! motionSensor
  extern MotionSensor motionSensor;

  //! prmDb
  extern Svc::PrmDb prmDb;

  //! rateGroup1Comp
  extern Svc::ActiveRateGroup rateGroup1Comp;

  //! rateGroup2Comp
  extern Svc::ActiveRateGroup rateGroup2Comp;

  //! rateGroup3Comp
  extern Svc::ActiveRateGroup rateGroup3Comp;

  //! rateGroupDriverComp
  extern Svc::RateGroupDriver rateGroupDriverComp;

  //! staticMemory
  extern Svc::StaticMemory staticMemory;

  //! systemResources
  extern Svc::SystemResources systemResources;

  //! textLogger
  extern Svc::PassiveTextLogger textLogger;

  //! uplink
  extern Svc::Deframer uplink;

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  //! Initialize components
  void initComponents(
      const TopologyState& state //!< The topology state
  );

  //! Configure components
  void configComponents(
      const TopologyState& state //!< The topology state
  );

  //! Set component base Ids
  void setBaseIds();

  //! Connect components
  void connectComponents();

  //! Register commands
  void regCommands();

  //! Start tasks
  void startTasks(
      const TopologyState& state //!< The topology state
  );

  //! Stop tasks
  void stopTasks(
      const TopologyState& state //!< The topology state
  );

  //! Free threads
  void freeThreads(
      const TopologyState& state //!< The topology state
  );

  //! Tear down components
  void tearDownComponents(
      const TopologyState& state //!< The topology state
  );

  // ----------------------------------------------------------------------
  // Setup and teardown functions
  // ----------------------------------------------------------------------

  //! Set up the topology
  void setup(
      const TopologyState& state //!< The topology state
  );

  //! Tear down the topology
  void teardown(
      const TopologyState& state //!< The topology state
  );

}

#endif
